---

- hosts: localhost
  become: true
  vars:
    proxy_server: 127.0.0.1
    cj_nexus_ip: "{{ ansible_eth0.ipv4.address }}"
  roles:
    - role: oracle-java
    - role: nexus
      tags: nexus
    - role: simple-docker-daemon
    - role: juseppe
    - role: custom-jenkins
