---

- hosts: localhost
  become: true
  vars:
    proxy_server: 127.0.0.1
  roles:
    - role: oracle-java
    - role: nexus
      tags: nexus
    - role: client-tools
      tags: client-tools
    - role: simple-docker-daemon
      tags: juseppe
    - role: juseppe
      tags: juseppe
    - role: custom-jenkins
      tags: jenkins
